---
services:
  proxy:
    container_name: nginx
    image: nginx@sha256:97d490c12ba55b4946b01546d1c3ed324e8d41ab1c9fcb2a616aa470620e5b46 #1.30.4-alpine
    env_file:
      - ./.env
    volumes:
    - ./default.conf.template:/etc/nginx/templates/default.conf.template:ro
    # - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped