---
version: "2.1"
services:
  nginx:
    image: nginx
    container_name: web
    volumes:
      - ${PWD}/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - default

networks:
  default:
    name: wireguard_default
    external: true
#     driver: bridge
#     ipam:
#       config:
#         - subnet: 192.168.1.0/24