---
services:
  sync:
    container_name: syncthing
    image: syncthing/syncthing
    post_start:
    - command: ip route add 172.19.1.0/24 via 172.19.0.2
      user: root
    hostname: hostname
    env_file:
      - .env
    environment:
      - PUID=1000
      - PGID=1000
      - STGUIADDRESS=
    volumes:
      # - $PWD/data:/var/syncthing
      - /srv/syncthing:/var/syncthing
    ports:
      # - 8384:8384 # Web UI
      # - 22000:22000/tcp # TCP file transfers
      # - 22000:22000/udp # QUIC file transfers
      # - 21027:21027/udp # Receive local discovery broadcasts
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    networks:
      default:
        ipv4_address: 172.19.0.4

networks:
  default:
    name: vpn_default
    external: true