---
version: "3"
services:
  syncthing:
    image: syncthing/syncthing
    container_name: syncthing
    hostname: hostname
    environment:
      - PUID=1000
      - PGID=1000
      #- STGUIADDRESS=
    volumes:
      # - $PWD/data:/var/syncthing
      - /srv/syncthing:/var/syncthing
    ports:
      - 8384:8384 # Web UI
      - 22000:22000/tcp # TCP file transfers
      - 22000:22000/udp # QUIC file transfers
      - 21027:21027/udp # Receive local discovery broadcasts
    restart: unless-stopped
    networks:
      - default

networks:
  default:
    name: wireguard_default
    external: true
#     driver: bridge
#     ipam:
#       config:
#         - subnet: 192.168.1.0/24