---
version: "2.1"
services:
  wireguard:
    image: lscr.io/linuxserver/wireguard:latest
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    env_file:
      - ${PWD}/.env
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Manila
      # - SERVERURL=example.domain.com
      - SERVERPORT=51820 
      # - PEERS=peer1,peer2,peer3
      - PEERDNS=auto
      - INTERNAL_SUBNET=10.0.0.0 
      - ALLOWEDIPS=0.0.0.0/0 
      - LOG_CONFS=true
    volumes:
      - ${PWD}/config:/config
      - ${PWD}/modules:/lib/modules
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
    restart: unless-stopped
    networks:
      default:
        ipv4_address: 192.168.1.2

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24