---
services:
  vpn:
    container_name: wireguard
    image: lscr.io/linuxserver/wireguard:latest
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    env_file:
      - ${PWD}/.env
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Manila
      # - SERVERURL=example.domain.com
      - SERVERPORT=51820
      # - PEERS=peer1,peer2,peer3
      - PEERDNS=172.19.0.3
      - INTERNAL_SUBNET=172.19.1.0/24
      - ALLOWEDIPS=0.0.0.0/0,::0/0
      - PERSISTENTKEEPALIVE_PEERS=all
      - LOG_CONFS=true
    volumes:
      - ${PWD}/config:/config
      - ${PWD}/modules:/lib/modules
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
    restart: unless-stopped
    networks:
      default:
        ipv4_address: 172.19.0.2

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.0/24
          gateway: 172.19.0.1