---
version: "2.1"
services:
  wireguard:
    image: lscr.io/linuxserver/wireguard:latest
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Manila
      - SERVERURL=example.domain.com
      - SERVERPORT=51820 
      - PEERS=peer1,peer2,peer3
      - PEERDNS=auto
      - INTERNAL_SUBNET=10.9.9.0 
      - ALLOWEDIPS=0.0.0.0/0 
      - LOG_CONFS=true
    volumes:
      - ${PWD}/config:/config
      - ${PWD}/modules:/lib/modules
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
